version: "2"

linters:
  default: all

  disable:
    - wsl
    - depguard
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - godot
    - mnd
    - noinlineerr
    - cyclop
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl_v5

  exclusions:
    rules:
      - path: dagger/cli\.go
        linters:
          - gosec
        text: "G204"
      - path: config/save\.go
        text: "G304"
      - path: config/load\.go
        text: "G304"

      # Exclude comments rules from revive linter
      - linters:
          - revive
        text: "should have comment"
      - linters:
          - revive
        text: "package-comments: should have a package comment"

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - golines

run:
  timeout: 5m

  