name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: 1.25.1

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: 2.5.0

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Compile dagbench using dagger
        uses: dagger/dagger-for-github@v8.2.0
        with:
          version: "v0.19.2"
          args: --cloud -c 'bin --platform linux/amd64 | export dagbench'
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: Run dagbench help
        run: dagbench --help