name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
      - "**/.github/workflows/publish.yaml"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
      - "**/.github/workflows/publish.yaml"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: 1.25.1

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Compile dagbench using dagger
        uses: dagger/dagger-for-github@v8.2.0
        with:
          version: "v0.19.2"
          shell: bin --platform linux/amd64 | export dagbench
          dagger-flags: --cloud
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: Run dagbench help
        run: ./dagbench --help

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run integration tests
        uses: dagger/dagger-for-github@v8.2.0
        with:
          version: "v0.19.2"
          shell: integration-test
          dagger-flags: --cloud
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}